import type { AstrologyReport } from "../../types/astrology";

export const MOCK_ASTROLOGY_REPORTS: AstrologyReport[] = [
  {
    id: "birth-chart-report",
    title: "Birth Chart Report",
    subtitle: "The full personality map: planets, houses, aspects, and dominant energy.",
    status: "locked",
    unlockHint: "Built from a saved chart with placements, houses, elements, modalities, and aspect patterns.",
    previewBullets: ["Big Three and chart ruler", "Dominant element and house emphasis", "Key aspect patterns in plain language"],
  },
  {
    id: "love-pattern",
    title: "Love Pattern",
    subtitle: "How you bond, desire, protect, and choose closeness.",
    status: "locked",
    unlockHint: "Prepared from Venus, Mars, Moon, the 5th house, and the 7th house.",
    previewBullets: ["Venus and Mars style", "Emotional safety needs", "Relationship habits to notice"],
  },
  {
    id: "career-direction",
    title: "Career Direction",
    subtitle: "Work rhythm, public signal, and where discipline becomes useful.",
    status: "locked",
    unlockHint: "Prepared from Midheaven, 10th house, Saturn, Mars, Jupiter, and active transits.",
    previewBullets: ["Public signal and timing", "Skill-building pressure points", "Where consistency pays off"],
  },
  {
    id: "money-map",
    title: "Money Map",
    subtitle: "Earning style, resource pressure, and how safety becomes real.",
    status: "locked",
    unlockHint: "Prepared from the 2nd and 8th houses, Venus, Jupiter, Saturn, and current timing.",
    previewBullets: ["Earning and spending style", "Resource growth windows", "Where restraint protects you"],
  },
  {
    id: "monthly-pattern",
    title: "Month Ahead",
    subtitle: "The emotional rhythm, moon cycle, and transit windows of the next 30 days.",
    status: "locked",
    unlockHint: "Requires a saved birth profile, moon phase context, and a full transit window.",
    previewBullets: ["Peak transits ranked by date", "Moon-cycle emotional weather", "Practical reflection prompts"],
  },
  {
    id: "year-ahead-2026",
    title: "Year Ahead",
    subtitle: "Major themes, pressure points, and clean openings for the year.",
    status: "locked",
    unlockHint: "Built from annual transits, natal house emphasis, and solar-return-style themes.",
    previewBullets: ["Quarter-by-quarter timing", "Growth and restraint patterns", "Clean openings to watch"],
  },
  {
    id: "solar-return",
    title: "Solar Return",
    subtitle: "Birthday-to-birthday theme, yearly emphasis, and where attention gathers.",
    status: "locked",
    unlockHint: "Prepared from the user's birthday-year sky and the saved natal chart.",
    previewBullets: ["Birthday-year focus", "House emphasis for the year", "Personal reset questions"],
  },
  {
    id: "lunar-return",
    title: "Lunar Return",
    subtitle: "A monthly emotional reset based on the Moon returning to its natal place.",
    status: "locked",
    unlockHint: "Prepared from natal Moon placement and monthly lunar timing.",
    previewBullets: ["Monthly emotional theme", "Support and recovery windows", "One thing to release"],
  },
  {
    id: "saturn-return",
    title: "Saturn Return",
    subtitle: "Maturity, pressure, responsibility, and the structure becoming real.",
    status: "locked",
    unlockHint: "Most relevant near Saturn return ages; still previewed as a long-cycle growth lens.",
    previewBullets: ["Responsibility patterns", "Long-cycle pressure points", "What asks for structure"],
  },
  {
    id: "relationship-report",
    title: "Relationship Report",
    subtitle: "Two charts, one shared pattern, and the questions worth asking with consent.",
    status: "locked",
    unlockHint: "Requires consent from both people or a private manual partner entry.",
    previewBullets: ["Shared aspects without scoring", "Communication and tension cues", "Consent-first conversation prompts"],
  },
  {
    id: "shadow-pattern",
    title: "Shadow Growth",
    subtitle: "Repeating defenses, private fears, and how to work with them without fatalism.",
    status: "locked",
    unlockHint: "A reflective report built from Saturn, Chiron-style themes, Pluto, and the North Node lens.",
    previewBullets: ["Defensive loops by placement", "Private pressure patterns", "Growth edge without certainty"],
  },
  {
    id: "timing-windows",
    title: "Timing Windows",
    subtitle: "Key dates, active transits, and when to ask for a deeper timing read.",
    status: "locked",
    unlockHint: "Prepared from current transits, ranked windows, and saved natal chart context.",
    previewBullets: ["Current and upcoming windows", "Do / avoid timing prompts", "Dates worth watching"],
  },
];
